// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePage(arg1) {
  return window['go']['main']['App']['CreatePage'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function GetPages() {
  return window['go']['main']['App']['GetPages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadContent() {
  return window['go']['main']['App']['LoadContent']();
}

export function SaveContent(arg1) {
  return window['go']['main']['App']['SaveContent'](arg1);
}

export function SavePages(arg1) {
  return window['go']['main']['App']['SavePages'](arg1);
}

export function UpdatePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePage'](arg1, arg2, arg3);
}
