// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreatePage(arg1:string):Promise<main.Page>;

export function DeletePage(arg1:string):Promise<void>;

export function GetPages():Promise<Array<main.Page>>;

export function Greet(arg1:string):Promise<string>;

export function LoadContent():Promise<string>;

export function SaveContent(arg1:string):Promise<void>;

export function SavePages(arg1:Array<main.Page>):Promise<void>;

export function UpdatePage(arg1:string,arg2:string,arg3:string):Promise<void>;
